"""empty message

Revision ID: 128f03164518
Revises: 
Create Date: 2020-05-03 23:10:31.406749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128f03164518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('complemento', sa.String(length=25), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    op.create_table('telefones',
    sa.Column('id_telefone', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=11), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_telefone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefones')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
