"""empty message

Revision ID: ea20890a8477
Revises: 
Create Date: 2020-05-25 20:30:12.576307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea20890a8477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicos',
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=False),
    sa.Column('preco', sa.String(length=60), nullable=False),
    sa.Column('duracao', sa.String(length=60), nullable=False),
    sa.Column('disponibilidade', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('funcionario', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('agendamento',
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id_servico'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    op.create_table('enderecos',
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('complemento', sa.String(length=25), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    op.create_table('telefones',
    sa.Column('id_telefone', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=11), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_telefone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefones')
    op.drop_table('enderecos')
    op.drop_table('agendamento')
    op.drop_table('usuarios')
    op.drop_table('servicos')
    # ### end Alembic commands ###
